site_name: CIT Resewn Docs
site_url: https://cit-resewn.rtfd.io

theme:
  name: readthedocs
  custom_dir: 'custom_theme/'
  highlightjs: true
  hljs_languages:
    - properties

plugins:
  - search

nav:
  - 'index.md'
  - CIT:
    - 'cit_base.md'
    - 'cit_item.md'
    - 'cit_elytra.md'
    - 'cit_armor.md'
    - 'cit_enchantment.md'
  - Misc:
    - 'global_properties.md'
    - 'api.md'
