site_name: CIT Resewn Docs
site_url: https://cit-resewn.rtfd.io

theme:
  name: readthedocs
  custom_dir: 'custom_theme/'
  collapse_by_default: false
  highlightjs: true
  hljs_languages:
    - properties

plugins:
    - search

nav:
    - Home: 'index.md'

