site_name: CIT Resewn Docs
site_url: https://citresewn.rtfd.io

theme:
  name: readthedocs
  custom_dir: 'custom_theme/'
  highlightjs: true
  hljs_languages:
    - properties

plugins:
  - search:
      separator: '[\s\-\`\.\/\\]+'

nav:
  - 'index.md'
  - Usage:
    - 'usage/users.md'
    - 'usage/config.md'
    - 'usage/pack_authors.md'
    - 'usage/mod_authors.md'
  - CIT:
    - 'cit/global.md'
    - 'cit/cit_base.md'
    - 'cit/cit_item.md'
    - 'cit/cit_elytra.md'
    - 'cit/cit_armor.md'
    - 'cit/cit_enchantment.md'
